spring:
  datasource:
    url: jdbc:mysql://120.24.93.68:3306/daliymanagement?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: utf-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: classpath:cn.itrover.homepage.bean
  config-location: classpath:mybatis-config.xml

config:
  jwt:
    secret: abcdefg1234567
    expire: 3600
    header: token
  cos:
    secretId: AKIDfEblEqvDfFbigP6HQIArNegT5RYXxo44
    secretKey: vA9tZ3II5edMqAIAnFTaS6f17yZw97pO
    regin: ap-chengdu
    url: https://daliymanager-1300698904.cos.ap-chengdu.myqcloud.com/
    bucketName: daliymanager-1300698904

logging:
  level:
    root: error
    cn.itrover.homepage: info
  file:
    name: log/homepage.log

server:
  port: 8082
debug: true
